var app=angular.module("calculator_app",[]);

app.controller('calculator_controller',function($scope)
{
	var stack= new Array();
	function readStack()
	{
		var retval="";
		for(var i=0;i<stack.length;i++)
		{
			retval+=stack[i];
		}
		return retval;
	}
	$scope.one=function()
	{
		stack.push("1");
		$scope.results=readStack();
	}
	$scope.two=function()
	{
		stack.push("2");
		$scope.results=readStack();
	}
	$scope.three=function()
	{
		stack.push("3");
		$scope.results=readStack();
	}
	$scope.four=function()
	{
		stack.push("4");
		$scope.results=readStack();
	}
	$scope.five=function()
	{
		stack.push("5");
		$scope.results=readStack();
	}
	$scope.six=function()
	{
		stack.push("6");
		$scope.results=readStack();
	}
	$scope.seven=function()
	{
		stack.push("7");
		$scope.results=readStack();
	}
	$scope.eight=function()
	{
		stack.push("8");
		$scope.results=readStack();
	}
	$scope.nine=function()
	{
		stack.push("9");
		$scope.results=readStack();
	}
	$scope.zero=function()
	{
		stack.push("0");
		$scope.results=readStack();
	}
	$scope.dot=function()
	{
		stack.push(".");
		$scope.results=readStack();
	}
	$scope.equals=function()
	{
		var temp=eval(readStack()).toString();
		stack=[];		
		stack.push(temp);
		$scope.results=readStack().toString();
	}
	$scope.del=function()
	{
		stack.pop();
		$scope.results=readStack();
	}
	$scope.add=function()
	{
		stack.push("+");
		$scope.results=readStack();
	}
	$scope.minus=function()
	{
		stack.push("-");
		$scope.results=readStack();
	}
	$scope.mult=function()
	{
		stack.push("*");
		$scope.results=readStack();
	}
	$scope.div=function()
	{
		stack.push("/");
		$scope.results=readStack();
	}
	
});